# R:\FinGPT-One\.streamlit\secrets.toml

TIINGO_API_KEY = "2c4969c77118ed400c13b704526c1431d31c6411"
FMP_API_KEY = "5C9DnMCAzYam2ZPjNpOxKLFxUiGhrJDD"
ALPHA_VANTAGE_API_KEY = "8UU32LX81NSED6CM"
GEMINI_API_KEY = "AIzaSyAK8BevJ1wIrwMoYDsnCLQXdZlFglF92WE"
NEWS_API_KEY = "874ba654bdcd4aa7b68f7367a907cc2f" 
